const projectsData = [
  // ==========================================
  // 2021
  // ==========================================
  {
    id: "golden-tree",
    year: 2021,
    name: "골든트리 (GOLDEN TREE)",
    location: "경기도 가평군",
    coordinates: [37.7538, 127.5309],
    plusCode: "QG4Q+5J",
    category: "F&B",
    englishTitle: "GOLDEN TREE",
    description: "북한강의 유려한 흐름과 사계절의 변화를 고스란히 담아낸 프리미엄 자연주의 카페 공간 브랜딩입니다. 자연과 건축의 조화를 시각화한 그래픽 모티프와 친환경 소재의 사이니지를 적용하였습니다.",
    image: "img/golden-tree.jpg",
    link: "https://identio.kr/goldentree",
    colorPalette: ["#D4B28C", "#2D3538", "#F7F5F0"],
    related: ["골든트리 시즌널 그래픽 (2024)", "트라이닷 (TRIDOT)", "리치티치 (Rich Teach)", "브렁크 (Brunk)"]
  },
  {
    id: "po-oak",
    year: 2021,
    name: "포옥 (Po.oak)",
    location: "경기도 포천시",
    coordinates: [37.8488, 127.1895],
    plusCode: "Q5F8+W8",
    category: "F&B",
    englishTitle: "PO.OAK",
    description: "숲속에 폭 둘러싸인 아늑한 휴식처의 감성을 모던하고 따뜻한 콘크리트 및 자연광 연출로 설계한 공간 브랜딩입니다. 계절의 온도를 담은 포옥 특유의 시각언어와 로고, 타이포그래피 시스템을 선보였습니다.",
    image: "img/po-oak.jpg",
    link: "https://identio.kr/pooak",
    colorPalette: ["#A68160", "#424242", "#F0ECE7"],
    related: ["포옥 시즌널 그래픽 (2022)"]
  },
  {
    id: "tridot",
    year: 2021,
    name: "트라이닷 (TRIDOT)",
    category: "Retail",
    englishTitle: "TRIDOT",
    description: "브랜드 아이덴티티 디자인 및 패키지 개발 프로젝트입니다.",
    colorPalette: ["#1C1D1F", "#CCCCCC"],
    related: ["골든트리 (GOLDEN TREE)"]
  },
  {
    id: "rich-teach",
    year: 2021,
    name: "리치티치 (Rich Teach)",
    category: "Education",
    englishTitle: "RICH TEACH",
    description: "교육 브랜드 리치티치의 아이덴티티 및 브랜딩 가이드라인 개발 프로젝트입니다.",
    colorPalette: ["#2B6CB0", "#FFFFFF"],
    related: ["브렁크 (Brunk)"]
  },
  {
    id: "brunk",
    year: 2021,
    name: "브렁크 (Brunk)",
    category: "Fashion",
    englishTitle: "BRUNK",
    description: "스포츠 패션 브랜드 브렁크의 통합 브랜드 경험(BX) 및 그래픽 시스템 프로젝트입니다.",
    colorPalette: ["#E53E3E", "#1A202C"],
    related: ["리치티치 (Rich Teach)"]
  },

  // ==========================================
  // 2022
  // ==========================================
  {
    id: "trivium",
    year: 2022,
    name: "트리비움 (IIIVIUM)",
    location: "경기도 평택시",
    coordinates: [37.0427, 127.0673],
    plusCode: "44R9+FM",
    category: "Complex",
    englishTitle: "IIIVIUM",
    description: "삼거리를 뜻하는 라틴어에서 영감을 받아, 세 갈래 길의 접점에 서서 조화를 이루는 프리미엄 주거 복합 문화공간의 아이덴티티입니다. 미니멀한 타이포그래피와 차분한 모노톤을 중심으로 세련된 공간 가치를 극대화했습니다.",
    image: "img/trivium.jpg",
    link: "https://identio.kr/trivium",
    colorPalette: ["#7A828A", "#1C1D1F", "#F5F5F7"],
    related: ["더휴식 (THE HOOSIK)", "오비오브 (obov)", "죽전 데이터센터 (CDC)"]
  },
  {
    id: "hotel-aank",
    year: 2022,
    name: "호텔 아늑 (HOTEL AANK)",
    location: "대전광역시",
    coordinates: [36.3504, 127.3845],
    plusCode: "983W+R2",
    category: "Hospitality",
    englishTitle: "HOTEL AANK",
    description: "집보다 더 아늑하고 편안한 쉼을 지향하는 부티크 호텔 브랜드의 공간 브랜딩 프로젝트입니다. 쉼의 본질에 집중할 수 있도록 자연광을 투과시키는 패브릭 소재와 웜 샌드 톤의 마감재를 조화롭게 구성했습니다.",
    image: "img/hotel-aank.jpg",
    link: "https://identio.kr/hotelannk",
    colorPalette: ["#D2B5A0", "#3E3B39", "#FBF9F6"],
    related: ["하이 스트리트 이탈리아", "(주)명산 (Meongsan)", "불스 NFT (BULLS NFT)"]
  },
  {
    id: "brand-new-machinery",
    year: 2022,
    name: "브랜뉴 머시너리 (brand-new machinery)",
    location: "경기도 화성시",
    coordinates: [37.2005, 126.9748],
    plusCode: "6M9X+85",
    category: "Factory",
    englishTitle: "BNM",
    description: "정밀 기계 및 산업 솔루션을 선도하는 기업의 스마트 팩토리 오피스 공간 브랜딩입니다. 차가운 메탈 소재에 활기찬 오렌지/블루 라인 포인트를 주어 기술력과 혁신성을 시각적으로 구현했습니다.",
    image: "img/bnm.jpg",
    link: "https://identio.kr/brandnewmachinery",
    colorPalette: ["#FF5E13", "#3B4A5A", "#E8ECEF"],
    related: ["진건종합건설 (JINGUN Constructure)", "우본개발 주식회사 (WOOBON)"]
  },
  {
    id: "jingun",
    year: 2022,
    name: "진건종합건설 (JINGUN Constructure)",
    location: "서울특별시",
    coordinates: [37.5665, 126.9780],
    plusCode: "G22R+68",
    category: "Construction",
    englishTitle: "JINGUN",
    description: "진건종합건설의 신사옥 공간 브랜딩 및 스페이스 아이덴티티(SI) 구축 프로젝트입니다.",
    image: "img/jingun.jpg",
    colorPalette: ["#1A365D", "#4A5568", "#EDF2F7"],
    related: ["브랜뉴 머시너리 (brand-new machinery)", "우본개발 주식회사 (WOOBON)"]
  },
  {
    id: "woobon",
    year: 2022,
    name: "우본개발 주식회사 (WOOBON)",
    location: "서울특별시",
    coordinates: [37.5600, 126.9700],
    plusCode: "F2Q7+4P",
    category: "Landscape Architecture",
    englishTitle: "WOOBON",
    description: "우본개발의 조경 공간 디자인 및 오피스 브랜딩 프로젝트입니다.",
    image: "img/woobon.jpg",
    colorPalette: ["#2F855A", "#2D3748", "#EDF2F7"],
    related: ["진건종합건설 (JINGUN Constructure)", "브랜뉴 머시너리 (brand-new machinery)"]
  },
  {
    id: "po-oak-seasonal",
    year: 2022,
    name: "포옥 시즌널 그래픽 (2022)",
    category: "Seasonal Graphics",
    englishTitle: "PO.OAK SEASONAL",
    description: "카페 포옥의 사계절 감성을 담아낸 시각 아이덴티티 및 그래픽 프레임웍입니다.",
    colorPalette: ["#A68160", "#CCCCCC"],
    related: ["포옥 (Po.oak)"]
  },
  {
    id: "the-hoosik",
    year: 2022,
    name: "더휴식 (THE HOOSIK)",
    category: "Hospitality",
    englishTitle: "THE HOOSIK",
    description: "중소형 호텔 위탁 운영 브랜드 더휴식의 브랜드 아이덴티티 구축 작업입니다.",
    colorPalette: ["#2C3E50", "#ECF0F1"],
    related: ["호텔 아늑 (HOTEL AANK)"]
  },
  {
    id: "obov",
    year: 2022,
    name: "오비오브 (obov)",
    category: "F&B",
    englishTitle: "OBOV",
    description: "커피와 미식을 즐기는 라이프스타일 카페 오비오브의 브랜드 리브랜딩 및 그래픽 패키지입니다.",
    colorPalette: ["#D35400", "#2C3E50"],
    related: ["골든트리 (GOLDEN TREE)"]
  },
  {
    id: "cdc",
    year: 2022,
    name: "죽전 데이터센터 (CDC)",
    category: "Naming",
    englishTitle: "CDC",
    description: "첨단 친환경 데이터센터 개발을 위한 브랜드 네이밍 및 비주얼 아이덴티티 디자인입니다.",
    colorPalette: ["#2980B9", "#2C3E50"],
    related: ["트리비움 (IIIVIUM)"]
  },
  {
    id: "high-street-italia",
    year: 2022,
    name: "하이 스트리트 이탈리아",
    category: "Retail",
    englishTitle: "HIGH STREET ITALIA",
    description: "이탈리아 무역공사 주관의 한국 내 공식 이탈리아 홍보관 하이 스트리트 이탈리아의 쇼룸 브랜딩입니다.",
    colorPalette: ["#27AE60", "#C0392B", "#FFFFFF"],
    related: ["호텔 아늑 (HOTEL AANK)"]
  },
  {
    id: "meongsan",
    year: 2022,
    name: "(주)명산 (Meongsan)",
    category: "Landscape Architecture",
    englishTitle: "MEONGSAN",
    description: "조경 디자인 전문 기업 명산의 브랜드 아이덴티티 리뉴얼 프로젝트입니다.",
    colorPalette: ["#1E824C", "#BDC3C7"],
    related: ["우본개발 주식회사 (WOOBON)"]
  },
  {
    id: "bulls-nft",
    year: 2022,
    name: "불스 NFT (BULLS NFT)",
    category: "Graphic",
    englishTitle: "BULLS NFT",
    description: "디지털 아트를 활용한 커뮤니티 프로젝트 불스 NFT의 비주얼 브랜딩 및 캐릭터 그래픽입니다.",
    colorPalette: ["#E74C3C", "#2C3E50"],
    related: ["호텔 아늑 (HOTEL AANK)"]
  },

  // ==========================================
  // 2023
  // ==========================================
  {
    id: "dalseong-jujo",
    year: 2023,
    name: "달성주조 (DALSEONG JUJO)",
    location: "대구광역시",
    coordinates: [35.7725, 128.4357],
    plusCode: "PCHM+2R",
    category: "F&B",
    englishTitle: "DALSEONG JUJO",
    description: "전통 방식 and 현대적 제조 기술을 접목한 프리미엄 수제 전통주 브랜드의 플래그십 양조장 겸 시음 공간입니다. 세월의 멋을 느낄 수 있는 고재와 발효의 온도를 상징하는 질그릇 톤을 융합했습니다.",
    image: "img/dalseong-jujo.jpg",
    link: "https://identio.kr/dalseong",
    colorPalette: ["#A0522D", "#2F2F2F", "#ECE5DD"],
    related: ["달성주조 패키지 (2025)", "모자이크 (MOZAIQ)"]
  },
  {
    id: "shltr",
    year: 2023,
    name: "셜터 (SHLTR)",
    location: "강원특별자치도 속초시",
    coordinates: [38.2046, 128.5912],
    plusCode: "5HXW+2W",
    category: "F&B",
    englishTitle: "SHLTR",
    description: "동해 바다의 거친 파도와 해안 암석에서 모티브를 얻은 오션뷰 카페/라운지 공간입니다. 거친 텍스처의 노출 콘크리트와 대비되는 거울 및 투명 아크릴 소재를 사용하여 시원한 바다 경관을 공간 내부로 적극 끌어들였습니다.",
    image: "img/shltr.jpg",
    link: "https://identio.kr/shltr",
    colorPalette: ["#4E5E6C", "#1B2228", "#DFE4E8"],
    related: ["프로젝트 서울 (PROJECT SEOUL)"]
  },
  {
    id: "hotel-simjak",
    year: 2023,
    name: "호텔 심작 (HOTEL SIMJAK)",
    location: "경기도 화성시",
    coordinates: [37.1995, 126.8315],
    plusCode: "639H+6C",
    category: "Hospitality",
    englishTitle: "HOTEL SIMJAK",
    description: "마음의 울림과 쉼의 온기를 담은 프라이빗 부티크 호텔입니다. '심작(心作)'이라는 네이밍에 맞춰 심장의 박동처럼 붉고 아스라한 조명 연출과 차분하게 톤 다운된 원목 마감으로 깊은 명상의 시간을 유도합니다.",
    image: "img/hotel-simjak.jpg",
    link: "https://identio.kr/hotelsimjak",
    colorPalette: ["#B83C3C", "#241C1C", "#F4F0EE"],
    related: ["포그막 (fogmag)"]
  },
  {
    id: "tennis-land",
    year: 2023,
    name: "테니스랜드 (TENNIS LAND)",
    location: "경상남도 창원시",
    coordinates: [35.2281, 128.6811],
    plusCode: "6M9Q+HR",
    category: "Sports",
    englishTitle: "TENNIS LAND",
    description: "도심 속에서 테니스를 즐길 수 있는 프리미엄 실내 테니스 코트 및 라운지 공간입니다. 테니스 코트 라인의 역동성을 살린 조명 연출과 상큼한 네온 그린 컬러 포인트로 활기찬 브랜드 아이덴티티를 심어줍니다.",
    image: "img/tennis-land.jpg",
    link: "https://identio.kr/tennisland1",
    colorPalette: ["#39FF14", "#1E2A3A", "#FFFFFF"],
    related: ["위어스 (weus)", "리커버 (RECOVER FITNESS)"]
  },
  {
    id: "mozaiq",
    year: 2023,
    name: "모자이크 (MOZAIQ)",
    category: "Hospitality",
    englishTitle: "MOZAIQ",
    description: "프리미엄 공간 경험을 제공하는 모자이크 브랜드의 비주얼 아이덴티티 디자인입니다.",
    image: "img/mozaiq.jpg",
    link: "https://identio.kr/mozaiq",
    colorPalette: ["#2C3E50", "#BDC3C7"],
    related: ["달성주조 (DALSEONG JUJO)"]
  },
  {
    id: "project-seoul",
    year: 2023,
    name: "프로젝트 서울 (PROJECT SEOUL)",
    category: "Exhibition",
    englishTitle: "PROJECT SEOUL",
    description: "서울의 정체성을 바탕으로 진행된 크리에이티브 전시 및 아트 브랜딩 프로젝트입니다.",
    colorPalette: ["#8E44AD", "#F1C40F"],
    related: ["셜터 (SHLTR)"]
  },
  {
    id: "fogmag",
    year: 2023,
    name: "포그막 (fogmag)",
    category: "F&B",
    englishTitle: "FOGMAG",
    description: "안개 속의 고요함을 품은 식문화 공간 브랜드 포그막의 통합 브랜딩 디자인입니다.",
    image: "img/fogmag.jpg",
    link: "https://identio.kr/fogmag",
    colorPalette: ["#7F8C8D", "#FFFFFF"],
    related: ["호텔 심작 (HOTEL SIMJAK)", "포그막 패키지 (2025)"]
  },

  // ==========================================
  // 2024
  // ==========================================
  {
    id: "pando",
    year: 2024,
    name: "판도 (PANDO)",
    location: "경기도 화성시",
    coordinates: [37.2039, 126.9578],
    plusCode: "5483+QH",
    category: "F&B",
    englishTitle: "PANDO",
    description: "비밀스러운 숲과 온화한 온기를 품은 복합 문화공간 브랜드입니다. 천연석 조형물과 깊이 있는 우드 텍스처를 조합해 도심을 벗어난 초자연적 감성을 공간과 시각 매체 전반에 걸쳐 유기적으로 투영했습니다.",
    image: "img/pando.jpg",
    link: "https://identio.kr/pando",
    colorPalette: ["#708090", "#2E3B33", "#F5F5F0"],
    related: ["데포 (DEFFO)", "에이콘 (ACORN)", "큐디오 (QDO)", "시닉 (SCENIC)"]
  },
  {
    id: "recover-fitness",
    year: 2024,
    name: "리커버 (RECOVER FITNESS)",
    location: "서울특별시",
    coordinates: [37.5665, 126.9780],
    plusCode: "F4VC+JW",
    category: "Sports",
    englishTitle: "RECOVER FITNESS",
    description: "신체의 회복과 충전을 도모하는 하이엔드 웰니스 피트니스 센터 브랜딩입니다. 편안한 휴식을 돕는 자연 유기적 곡선 라인과 조도를 낮춘 간접 조명, 그리고 내추럴 톤의 세라믹 마감재를 주로 사용했습니다.",
    image: "img/recover-fitness.jpg",
    link: "https://identio.kr/RECOVER",
    colorPalette: ["#A3B19B", "#2B3A2C", "#F4F6F2"],
    related: ["엠페오 (MFEO)", "투어펏 (TOURPUTT)", "이니바이오 (IniBio)"]
  },
  {
    id: "omshanti",
    year: 2024,
    name: "옴샨티 (OMSHANTI)",
    location: "경상남도 창원시",
    coordinates: [35.2150, 128.6750],
    plusCode: "6MQJ+V4",
    category: "Fragrance",
    englishTitle: "OMSHANTI",
    description: "평화와 안녕을 기원하는 인도 샨티 주문에서 영감을 받은 요가 및 명상 센터입니다. 거친 천연 황토 벽과 대나무, 리넨 패브릭을 활용하여 신체의 감각을 깨우는 영성적인 힐링 무드를 자아냅니다.",
    image: "img/omshanti.jpg",
    link: "https://identio.kr/omshanti",
    colorPalette: ["#C2B280", "#4A3B32", "#FFFDD0"],
    related: ["위어스 (weus)"]
  },
  {
    id: "weus",
    year: 2024,
    name: "위어스 (weus)",
    location: "경상남도 창원시",
    coordinates: [35.2280, 128.6810],
    plusCode: "6M8R+MR",
    category: "Sports",
    englishTitle: "WEUS",
    description: "스포츠 브랜드 위어스의 프리미엄 트레이닝 및 피트니스 라운지 공간입니다. 브랜드를 상징하는 강렬한 컬러 포인트와 격자 그리드를 시각 디자인 및 가구 배치에 조화롭게 연출했습니다.",
    image: "img/weus.jpg",
    colorPalette: ["#0052CC", "#FF5630", "#F4F5F7"],
    related: ["리커버 (RECOVER FITNESS)", "테니스랜드 (TENNIS LAND)"]
  },
  {
    id: "golden-tree-seasonal",
    year: 2024,
    name: "골든트리 시즌널 그래픽 (2024)",
    category: "Seasonal Graphics",
    englishTitle: "GOLDEN TREE",
    description: "가평 골든트리의 2024 계절 그래픽 연출 작업입니다. 자연의 색상을 현대적인 그래픽 톤으로 변환하였습니다.",
    image: "img/golden-tree-seasonal-graphic.jpg",
    colorPalette: ["#D4B28C", "#2D3538"],
    related: ["골든트리 (GOLDEN TREE)"]
  },
  {
    id: "deffo",
    year: 2024,
    name: "데포 (DEFFO)",
    category: "Fashion",
    englishTitle: "DEFFO",
    description: "패션 레이블 데포(DEFFO)의 통합 brand 아이덴티티 및 룩북 비주얼 디렉션입니다.",
    colorPalette: ["#2c2c2c", "#ffffff"],
    related: ["판도 (PANDO)"]
  },
  {
    id: "acorn",
    year: 2024,
    name: "에이콘 (ACORN)",
    category: "F&B",
    englishTitle: "ACORN",
    description: "도토리와 자연에서 영감을 받은 베이커리 카페 에이콘의 정체성과 포장 디자인입니다.",
    colorPalette: ["#8B5A2B", "#F5F5DC"],
    related: ["판도 (PANDO)"]
  },
  {
    id: "qdo",
    year: 2024,
    name: "큐디오 (QDO)",
    category: "Cultural Complex",
    englishTitle: "QDO",
    description: "문화 예술 콘텐츠 플랫폼 큐디오의 그래픽 및 브랜딩 가이드입니다.",
    colorPalette: ["#2980B9", "#E74C3C"],
    related: ["판도 (PANDO)"]
  },
  {
    id: "scenic",
    year: 2024,
    name: "시닉 (SCENIC)",
    category: "Landscape Architecture",
    englishTitle: "SCENIC",
    description: "자연을 그리는 조경 브랜드 시닉의 아이덴티티 및 슬로건 정비 프로젝트입니다.",
    colorPalette: ["#27AE60", "#FFFFFF"],
    related: ["판도 (PANDO)", "엠페오 (MFEO)"]
  },
  {
    id: "mfeo",
    year: 2024,
    name: "엠페오 (MFEO)",
    category: "Landscape Architecture",
    englishTitle: "MFEO",
    description: "프리미엄 리빙 및 가드닝 전문 브랜드 MFEO의 시각 브랜딩 및 굿즈 그래픽입니다.",
    image: "img/mfeo.jpg",
    link: "https://identio.kr/mfeo",
    colorPalette: ["#3E2723", "#D7CCC8"],
    related: ["시닉 (SCENIC)", "리커버 (RECOVER FITNESS)"]
  },
  {
    id: "tourputt",
    year: 2024,
    name: "투어펏 (TOURPUTT)",
    category: "Golf",
    englishTitle: "TOURPUTT",
    description: "증강현실(AR) 기반 정밀 골프 퍼팅 훈련 브랜드 투어펏의 로고 및 UI 그래픽 에센셜입니다.",
    colorPalette: ["#1E2A38", "#00FF66"],
    related: ["리커버 (RECOVER FITNESS)"]
  },
  {
    id: "inibio",
    year: 2024,
    name: "이니바이오 (IniBio)",
    category: "Healthcare",
    englishTitle: "INIBIO",
    description: "바이오 테크놀로지 벤처 기업 이니바이오의 통합 리브랜딩 및 CI 디자인 가이드라인입니다.",
    image: "img/inibio.jpg",
    colorPalette: ["#0F4C81", "#CCCCCC"],
    related: ["리커버 (RECOVER FITNESS)"]
  },

  // ==========================================
  // 2025
  // ==========================================
  {
    id: "lemaha",
    year: 2025,
    name: "르마하 (Lémaha)",
    location: "서울특별시",
    coordinates: [37.5186, 127.0210],
    plusCode: "GXFW+QC",
    category: "Beauty",
    englishTitle: "LEMAHA",
    description: "고급 에스테틱 및 스킨케어 브랜드의 플래그십 쇼룸과 트리트먼트 룸 공간 디자인입니다. 물결처럼 부드러운 우윳빛 아치 벽체와 골드 메탈을 배치하여 럭셔리 웰니스 라이프스타일을 대변합니다.",
    image: "img/lemaha.jpg",
    link: "https://identio.kr/lemaha",
    colorPalette: ["#E5D4C0", "#5C5248", "#FAF8F5"],
    related: ["르마하 패키지 (2026)", "네슬레 헬스 사이언스 스토어", "롯데 오화 (Lotte OHWA)", "코브엔터 (COV Entertainment)", "리그서울 (League Seoul)"]
  },
  {
    id: "tp-tower-signage",
    year: 2025,
    name: "TP타워 사이니지 (TP TOWER Signage)",
    location: "서울특별시",
    coordinates: [37.5218, 126.9242],
    plusCode: "GWCF+G6",
    category: "Signage Design",
    englishTitle: "TP TOWER",
    description: "여의도 금융 중심지에 위치한 랜드마크 타워의 통합 길찾기(Wayfinding) 및 웨이파인딩 사이니지 환경 그래픽 프로젝트입니다. 현대적인 타이포그래피와 미니멀한 픽토그램을 활용해 직관적인 정보 흐름을 설계했습니다.",
    image: "img/tp-tower-signage.jpg",
    colorPalette: ["#1F2937", "#4B5563", "#F3F4F6"],
    related: ["진건종합건설 (JINGUN Constructure)"]
  },
  {
    id: "le-salon",
    year: 2025,
    name: "르살롱 (LE SALON)",
    location: "경기도 성남시",
    coordinates: [37.3917, 127.1118],
    plusCode: "94P7+6V",
    category: "Landscape Architecture",
    englishTitle: "LE SALON",
    description: "유러피안 헤리티지를 현대적으로 재해석한 하이엔드 살롱앤바(Salon & Bar)의 공간 경험 디자인입니다. 짙은 에메랄드 그린 컬러의 가죽 가구와 클래식한 몰딩 마감에 감각적인 현대 회화 작품을 조화시켰습니다.",
    image: "img/le-salon.jpg",
    link: "https://identio.kr/lesalon",
    colorPalette: ["#0F4C3A", "#332211", "#F6F5F2"],
    related: ["포시 (Posi)"]
  },
  {
    id: "nuwa-clinic",
    year: 2025,
    name: "너와의원 (NUWA CLINIC)",
    location: "서울특별시",
    coordinates: [37.5412, 127.0435],
    plusCode: "F2WH+R2",
    category: "Healthcare",
    englishTitle: "NUWA CLINIC",
    description: "성수동의 인더스트리얼 러프함 속에서 편안함을 찾는 프리미엄 안티에이징 클리닉입니다. 메디컬 특유의 차가움을 상쇄하기 위해 코랄 샌드 질감의 도장과 둥근 천장 라인 디자인을 적용해 심리적 안정감을 제공합니다.",
    image: "img/nuwa-clinic.jpg",
    link: "https://identio.kr/nuwaclinic",
    colorPalette: ["#E8D3C9", "#403D3B", "#FAF8F6"],
    related: ["네슬레 헬스 사이언스 스토어", "르마하 (Lémaha)"]
  },
  {
    id: "deli-mart",
    year: 2025,
    name: "델리마트 (Deli Mart)",
    location: "충청남도 아산시",
    coordinates: [36.7898, 127.0024],
    plusCode: "Q3R8+FH",
    category: "Grocery Retail",
    englishTitle: "DELI MART",
    description: "글로벌 미식 식자재와 캐주얼 다이닝을 한곳에서 즐길 수 있는 식료품 마켓 및 식당 공간입니다. 경쾌한 옐로우와 레드 계열의 컬러 매치와 빈티지 식료품 상점 무드의 그래픽을 더해 신선함을 전달합니다.",
    image: "img/deli-mart.jpg",
    link: "https://identio.kr/delimart",
    colorPalette: ["#FF3B30", "#FFCC00", "#F2F2F7"],
    related: ["델리푸드 (Deli Food) (2026)"]
  },
  {
    id: "dalseong-package",
    year: 2025,
    name: "달성주조 패키지 (2025)",
    category: "F&B",
    englishTitle: "DALSEONG JUJO",
    description: "달성주조의 2025 리뉴얼 제품 패키지 및 브랜딩 가이드라인 디자인입니다.",
    colorPalette: ["#A0522D", "#2F2F2F"],
    related: ["달성주조 (DALSEONG JUJO)"]
  },
  {
    id: "fogmag-package",
    year: 2025,
    name: "포그막 패키지 (fogmag Package)",
    category: "F&B",
    englishTitle: "FOGMAG",
    description: "F&B 브랜드 포그막의 시즌 패키지 및 리미티드 에디션 포장 박스 비주얼 디자인입니다.",
    colorPalette: ["#7F8C8D", "#CCCCCC"],
    related: ["포그막 (fogmag)"]
  },
  {
    id: "nestle-health-store",
    year: 2025,
    name: "네슬레 헬스 사이언스 스토어",
    category: "Healthcare",
    englishTitle: "NESTLE",
    description: "네슬레 헬스 사이언스의 온라인 공식 스토어 및 제품 브랜딩 가이드라인 설계입니다.",
    image: "img/nestle.jpg",
    link: "https://identio.kr/works",
    colorPalette: ["#005A9C", "#FFD100"],
    related: ["너와의원 (NUWA CLINIC)", "르마하 (Lémaha)"]
  },
  {
    id: "lotte-ohwa",
    year: 2025,
    name: "롯데 오화 (Lotte OHWA)",
    category: "F&B",
    englishTitle: "LOTTE OHWA",
    description: "롯데의 신규 F&B 브랜드 오화(OHWA)의 브랜드 콘셉트 빌딩 및 통합 비주얼 아이덴티티입니다.",
    colorPalette: ["#8B0000", "#FFFFFF"],
    related: ["르마하 (Lémaha)"]
  },
  {
    id: "cov-entertainment",
    year: 2025,
    name: "코브엔터 (COV Entertainment)",
    category: "Sports",
    englishTitle: "COV ENTERTAINMENT",
    description: "스포츠 전문 엔터테인먼트 기업 코브엔터의 통합 BX 시스템 구축 프로젝트입니다.",
    image: "img/cov.jpg",
    link: "https://identio.kr/cov",
    colorPalette: ["#2C3E50", "#F39C12"],
    related: ["리그서울 (League Seoul)", "르마하 (Lémaha)"]
  },
  {
    id: "league-seoul",
    year: 2025,
    name: "리그서울 (League Seoul)",
    category: "Sports",
    englishTitle: "LEAGUE SEOUL",
    description: "스포츠 리그 플랫폼 리그서울의 시각 정체성 및 전용 어플리케이션 UI 가이드입니다.",
    colorPalette: ["#000080", "#FF4500"],
    related: ["코브엔터 (COV Entertainment)", "르마하 (Lémaha)"]
  },
  {
    id: "posi",
    year: 2025,
    name: "포시 (Posi)",
    category: "Healthcare",
    englishTitle: "POSI",
    description: "라이프스타일 헬스케어 브랜드 포시의 네이밍 및 시각 아이덴티티 시스템입니다.",
    image: "img/posi.jpg",
    colorPalette: ["#4A90E2", "#FFFFFF", "#1C1D1F"],
    related: ["르살롱 (LE SALON)"]
  },

  // ==========================================
  // 2026
  // ==========================================
  {
    id: "wilson-homecourt",
    year: 2026,
    name: "윌슨 홈코트 시리즈 (Wilson Homecourt Series)",
    location: "경기도 구리시",
    coordinates: [37.6026, 127.1432],
    plusCode: "H489+P3",
    category: "Sports",
    englishTitle: "WILSON HOMECOURT",
    description: "글로벌 스포츠 브랜드 윌슨의 프리미엄 농구 및 라이프스타일 팝업 체험 공간입니다. 농구 코트 바닥면의 러프한 텍스처와 격자형 철망, 강렬한 화이트/오렌지 라인을 결합해 도심 스트릿 코트 무드를 고스란히 담아냈습니다.",
    image: "img/whs.jpg",
    link: "https://identio.kr/whs",
    colorPalette: ["#C8102E", "#2B2B2A", "#FFFFFF"],
    related: ["기아 이음 플랫플랫 (Kia Eeum flatflat)"]
  },
  {
    id: "giun-sangja",
    year: 2026,
    name: "기운상자 (Giun Sangja)",
    location: "경상남도 창원시",
    coordinates: [35.2255, 128.6820],
    plusCode: "4G2X+H7",
    category: "F&B",
    englishTitle: "GIUN SANGJA",
    description: "로컬 농산물을 세련되게 담아 도시민에게 유통하는 프리미엄 로컬 그로서리숍입니다. 박스 패키지 형태에서 모티브를 딴 반듯하고 절제된 목조 가구 배치로 신뢰와 바른 기운을 공간 전체에 채웠습니다.",
    image: "img/giunsangja.jpg",
    colorPalette: ["#8B5A2B", "#3A5FCD", "#F5F5DC"],
    related: ["소료 (SORYO)"]
  },
  {
    id: "chungkiwa-garden",
    year: 2026,
    name: "청기와가든 (Chungkiwa Garden)",
    location: "서울특별시",
    coordinates: [37.5562, 126.9227],
    plusCode: "GWFG+JC",
    category: "Restaurant",
    englishTitle: "CHUNGKIWA GARDEN",
    description: "대형 한식 가든 브랜드를 트렌디하고 모던한 미니멀 다이닝 홀로 리브랜딩한 공간 프로젝트입니다. 전통 청기와 지붕의 곡선을 극도로 미니멀하게 추상화하여 벽체 디자인에 반영하고, 은은한 간접 조명을 심어 모던 미니멀리즘을 선사합니다.",
    image: "img/chungkiwa-garden.jpg",
    colorPalette: ["#1F3A3D", "#2E2A25", "#F7F6F3"],
    related: []
  },
  {
    id: "gtws",
    year: 2026,
    name: "GTWS (Golden Trail World Series)",
    location: "전북특별자치도 무주군",
    coordinates: [36.0071, 127.6606],
    plusCode: "VP5W+XG",
    category: "Sports",
    englishTitle: "GTWS",
    description: "무주 구천동 산악 일대에서 개최된 글로벌 트레일 러닝 대회의 베이스캠프 및 이벤트 아웃도어 공간입니다. 웅장한 대자연을 훼손하지 않는 친환경 조립식 파빌리온 구조물과 강인한 오렌지 톤의 비주얼 사인보드를 유기적으로 엮었습니다.",
    image: "img/gtws.jpg",
    colorPalette: ["#E65100", "#1B1B1B", "#EEEEEE"],
    related: []
  },
  {
    id: "jinju-observatory",
    year: 2026,
    name: "진주 전망대 (Jinju Observatory)",
    location: "경상남도 진주시",
    coordinates: [35.1802, 128.0847],
    plusCode: "53GG+8J",
    category: "Cultural Complex",
    englishTitle: "JINJU OBSERVATORY",
    description: "역사적인 도시 진주를 조망할 수 있는 산정상의 공공 전망대 및 쉼터 공간 디자인입니다. 주변 숲과 지형의 높낮이에 맞춘 나선형 덱(Deck) 동선을 배치하고, 밤에는 은은한 빛의 산책로가 되도록 인터랙티브 조명 설계를 병행하였습니다.",
    image: "img/jinju.jpg",
    colorPalette: ["#6D5A47", "#1E2A1A", "#F5F5F0"],
    related: []
  },
  {
    id: "lemaha-package",
    year: 2026,
    name: "르마하 패키지 (2026)",
    category: "Beauty",
    englishTitle: "LEMAHA",
    description: "스킨케어 브랜드 르마하의 2026 본품 및 선물용 제품 패키지 리뉴얼 비주얼 시스템입니다.",
    colorPalette: ["#E5D4C0", "#5C5248"],
    related: ["르마하 (Lémaha)"]
  },
  {
    id: "deli-food",
    year: 2026,
    name: "델리푸드 (Deli Food) (2026)",
    category: "F&B Retail",
    englishTitle: "DELI FOOD",
    description: "식자재 및 레디밀 브랜드 델리푸드의 푸드 패키지 디자인 및 레이블 일러스트레이션입니다.",
    colorPalette: ["#FF3B30", "#FFFFFF"],
    related: ["델리마트 (Deli Mart)"]
  },
  {
    id: "kia-eeum-flatflat",
    year: 2026,
    name: "기아 이음 플랫플랫 (Kia Eeum flatflat)",
    category: "F&B",
    englishTitle: "KIA EEUM",
    description: "기아 이음 프로젝트와 카페 플랫플랫의 파트너십 기념 콜라보레이션 F&B 브랜딩 키트입니다.",
    colorPalette: ["#000000", "#FFFFFF"],
    related: ["윌슨 홈코트 시리즈 (Wilson Homecourt Series)"]
  },
  {
    id: "soryo",
    year: 2026,
    name: "소료 (SORYO)",
    category: "Ceramics",
    englishTitle: "SORYO",
    description: "세라믹 공방 및 테이블웨어 브랜드 소료(SORYO)의 수공예 감성 브랜드 로고 및 패키지 개발입니다.",
    image: "img/soryo.jpg",
    colorPalette: ["#8C857B", "#FDFBF7"],
    related: ["기운상자 (Giun Sangja)"]
  }
];
